### ISSUE TITLE
What is the purpose of using setTimeout here?

### ISSUE THREAD

**Issue by spinoza1791** [juanjaho/animeGAN_Mobile#3]
From /components)/ProcessButton.js

What is the purpose of using setTimeout here? Why 500ms? What happens if there is no timeout set?
           
 setTimeout(
              () =>
                inferImage(
                  props.selectedImage,
                  props.outputMax,
                  props.setSelectedImage,
                  props.setIsLoadingScreen,
                  props.selectedModel
                ),
              500,

**Comment by juanjaho** [comment]
Hello, 

The 500ms is to let the front-end UI load before the inference begins. This is because the inference would start before the UI would update.  I coded this back when I was still unfamiliar with handling blocking processes. **_Using `setTimeout` is not the best practice._** 

A better way to do this today is to make use of [`InteractionManager`](https://reactnative.dev/docs/timers#interactionmanager) if you are developing in React Native, or to use [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) if you are developing WebApp (Browser based app). 

You can check out the implementation of [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) at my new [Project RTOD](https://github.com/juanjaho/real-time-object-detection-web-app). The usage of [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) can be found at [ObjectDetectionCamera.tsx](https://github.com/juanjaho/real-time-object-detection-web-app/blob/master/components/ObjectDetectionCamera.tsx#:~:text=requestAnimationFrame).

[Project RTOD](https://github.com/juanjaho/real-time-object-detection-web-app) utilizes real-time object detection to identify and label objects within an image or video stream. The model inference is done on the client side with no data sent to the backend. All of this while being accessible through the web. The app is a Progressive Web App meaning it provides a native-like experience (You can install it on your device to run it offline)

Do check it out :)

**Comment by spinoza1791** [comment]
Thank you! I will check it out.
